---
app:
    appPath: /offers
    port: 8000
    #logAddress: /var/log/interface/api-offers/trace.log
    logAddress: ./trace.log

database:
    host: 127.0.0.1
    #host: 172.29.20.32
    port: 27017
    database: service_layer
    table: offers
    supplementaryTable: supplementary_offers

categories:
    5:
        type: WEB_HOSTING
        category: DATACENTER
    6:
        type: VPS
        category: DATACENTER
    7:
        type: VIRTUAL_DATA_CENTER
        category: DATACENTER
    8:
        type: DEDICATED_SERVER
        category: DATACENTER
    9:
        type: HOUSE_LEASING
        category: DATACENTER
    10:
        type: YELLOW_PAGES
        category: YELLOW_PAGES
    11:
        type: DNS
        category: DATACENTER
    12:
        type: ACCESS
        category: DATACENTER
    13:
        type: VPN
        category: DATACENTER
        
privateApiTracking:
    #host: https://service-layer.private.etecsa.cu/offers
    host: http://localhost:8002/trackings/v1/
    # host: http://localhost:8000/offers