definitions:
  model.BSSOfferRequest:
    properties:
      offer:
        $ref: '#/definitions/model.BssOffer'
        type: object
    type: object
  model.BssAttached:
    properties:
      offeringID:
        type: string
      releationType:
        type: string
    type: object
  model.BssAttribute:
    properties:
      attr_code:
        type: string
      attr_type:
        type: string
      attr_value:
        type: string
      attr_value_desc:
        type: string
    type: object
  model.BssAttributeList:
    properties:
      attr:
        items:
          $ref: '#/definitions/model.BssAttribute'
        type: array
    type: object
  model.BssCatalog:
    properties:
      catalog_id:
        type: string
      catalog_name:
        type: string
    type: object
  model.BssCatalogList:
    properties:
      catalog:
        items:
          $ref: '#/definitions/model.BssCatalog'
        type: array
    type: object
  model.BssOffer:
    properties:
      attrList:
        $ref: '#/definitions/model.BssAttributeList'
        type: object
      bundle_flag:
        type: string
      catalogList:
        $ref: '#/definitions/model.BssCatalogList'
        type: object
      eff_date:
        type: string
      exp_date:
        type: string
      monthly_fee:
        type: number
      offer_cata:
        type: string
      offer_code:
        type: string
      offer_desc:
        type: string
      offer_id:
        type: string
      offer_name:
        type: string
      offer_type:
        type: string
      on_sale:
        type: string
      oneoff_fee:
        type: number
      pay_mode:
        type: string
      primary_flag:
        type: string
      relationshipList:
        $ref: '#/definitions/model.BssRelationshipList'
        type: object
      status:
        type: string
      topupFee:
        type: string
    type: object
  model.BssRelationshipList:
    properties:
      attached:
        items:
          $ref: '#/definitions/model.BssAttached'
        type: array
    type: object
  model.BssSyncOfferRequest:
    properties:
      syncOffers:
        items:
          $ref: '#/definitions/model.BSSOfferRequest'
        type: array
    type: object
  model.Offer:
    properties:
      category:
        type: string
      childrens:
        items:
          $ref: '#/definitions/model.Offer'
        type: array
      client_type:
        type: string
      code:
        type: string
      created_at:
        type: integer
      description:
        type: string
      expiration_date:
        type: integer
      external_id:
        type: string
      id:
        type: string
      metadata:
        additionalProperties:
          type: string
        type: object
      monthly_fee:
        type: number
      name:
        type: string
      one_of_fee:
        type: number
      pay_mode:
        type: string
      standalone:
        type: boolean
      updated_at:
        type: integer
    type: object
info:
  contact:
    email: sebastian.rodriguez@etecsa.cu
    name: Sebastian Rodriguez Mendez
  license: {}
paths:
  /health-check/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200": {}
      tags:
      - HealthCheck
  /v1/:
    get:
      consumes:
      - application/json
      parameters:
      - description: client id
        in: header
        name: x-client-id
        required: true
        type: string
      - description: offers status
        in: query
        name: active
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Offer'
            type: array
        "401":
          description: Unauthorized
          schema:
            type: Unauthorized
        "500":
          description: Internal Server Error
          schema:
            type: Server
      tags:
      - Search Offers
    post:
      consumes:
      - application/json
      parameters:
      - description: client id
        in: header
        name: x-client-id
        required: true
        type: string
      - description: offers to sync
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/model.BssSyncOfferRequest'
      produces:
      - application/json
      responses:
        "201": {}
        "400":
          description: Bad Request
          schema:
            type: Incorrect
        "401":
          description: Unauthorized
          schema:
            type: Unauthorized
        "500":
          description: Internal Server Error
          schema:
            type: Server
      summary: Create Offers from commercial system
      tags:
      - Create Offers Order
  /v1/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: client id
        in: header
        name: x-client-id
        required: true
        type: string
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Offer'
        "401":
          description: Unauthorized
          schema:
            type: Unauthorized
        "404":
          description: Not Found
          schema:
            type: Offer
        "500":
          description: Internal Server Error
          schema:
            type: Server
      tags:
      - Get Offer
swagger: "2.0"
